# Generated by Django 5.1.2 on 2025-12-14 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('university', models.CharField(blank=True, max_length=200)),
                ('points', models.IntegerField(default=0)),
                ('avatar', models.CharField(blank=True, max_length=10)),
                ('emoji', models.CharField(blank=True, default='⭐', max_length=10)),
                ('category', models.CharField(choices=[('global', 'Global'), ('university', 'University'), ('friends', 'Friends')], default='global', max_length=20)),
                ('is_university_entry', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Leaderboard Entries',
                'ordering': ['-points'],
            },
        ),
    ]
