# Generated by Django 5.1.2 on 2025-12-12 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
